DOC-12190 active/complete requests API
couchbaselabs/cb-swagger pull request #129
Opened 2024-05-30 18:10 UTC by ggray-cb

This covers the changes to the Analytics service admin API for active and completed requests.

[Here's a preview of the changes](https://preview.docs-test.couchbase.com/active-complete-requests-api/server/current/analytics/rest-admin.html). 

Note: this will need to wait until 7.6.2 is ready to ship before I can merge, because we currently don't have a staging branch in this repo.

2024-05-31 23:17 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The date and time when the request was created. +
the request's job

2024-05-31 23:18 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The ID of the request. This value can be null if request did not run (for example, due to an error). +
The job ID

2024-05-31 23:18 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|How long the request has been in the queue waiting to run. +
the job has been ...

2024-05-31 23:23 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|Seconds the request has been running. +
How long the request has been running in seconds.

2024-05-31 23:26 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The bytes of RAM being used to process this request. +
The memory required in bytes to run this request.

2024-05-31 23:28 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The state of the request. +
The state of the job.

2024-05-31 23:32 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +**Example** : `"RUNNING"`|enum (RUNNING, TERMINATED)
(PENDING, RUNNING, TERMINATED, FAILURE, FAILURE_BEFORE_EXECUTION)

2024-05-31 23:33 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The Analytics node running the request. +
The Analytics node that received the request.

2024-05-31 23:33 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The network address and port of the system that made the request. +
of the client that made the request.

2024-05-31 23:34 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The date and time the request was made. +
the request was received.

2024-05-31 23:38 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +**Example** : `"running"`|enum (running, completed)
(received, running, cancelled, completed)

2024-05-31 23:45 UTC, AliSolaiman commented on docs/modules/analytics/partials/rest-admin/definitions.adoc
> +__optional__|The date and time the request began running. +
the job began running.
OR
the request's job began running.

2024-06-13 11:55 UTC, simon-dew requested changes
LGTM, just one change requested.

I need to update the overall [Analytics REST API landing page](https://docs.couchbase.com/server/current/analytics/rest-analytics.html) to fit in with Tony's overall [REST API overview page](https://docs.couchbase.com/server/current/rest-api/rest-intro.html). I'll do this as part of DOC-12204. I'll update the Analytics REST API landing page to include the Active Requests and Completed Requests operations when I do so.

2024-06-13 11:55 UTC, simon-dew commented on src/analytics-admin/swagger/analytics-admin.yaml
You've stated that the Active Requests and Completed Requests operations take Analytics Manage / Analytics Select security. For consistency with the other operations, can you add links back from this security definition to these operations? (This isn't an essential part of the spec, I just added it for the convenience of readers.)

So, in the `securityDefinitions.Analytics Manage / Analytics Select.description` key, update the first full line of text in the description to say:

```markdown
For the [Active Requests](#_return_active_requests), [Request Cancellation](#_cancel_request), [Completed Requests](#_completed_requests), [Ingestion Status](#_ingestion_status), and [Pending Mutations](#_monitor_node) operations, users must have one of the following access roles:
```

2024-06-13 12:02 UTC, simon-dew commented
> Note: this will need to wait until 7.6.2 is ready to ship before I can merge, because we currently don't have a staging branch in this repo

Sorry for this oversight! I have created a `prerelease/7.6.2` branch for this repo and took the liberty to change the base branch for this pull request.

2024-06-14 13:50 UTC, simon-dew commented
> I need to update the overall [Analytics REST API landing page](https://docs.couchbase.com/server/current/analytics/rest-analytics.html) to fit in with Tony's overall [REST API overview page](https://docs.couchbase.com/server/current/rest-api/rest-intro.html). I'll do this as part of [DOC-12204](https://issues.couchbase.com/browse/DOC-12204). I'll update the Analytics REST API landing page to include the Active Requests and Completed Requests operations when I do so.

@ggray-cb as promised, I've opened a pull request to update the Analytics REST API landing page to include the Active Requests and Completed Requests operations here:

* https://github.com/couchbase/docs-server/pull/3605

2024-06-17 16:02 UTC, ggray-cb commented
OK, I believe I have addressed all the comments, and updated the preview site with the latest.

2024-06-26 10:53 UTC, simon-dew approved these changes
LGTM 👍 

Swagger2Markup is not putting the "Couchbase Server 7.6.2" tag where I wanted it to go, but looking at the [docs](http://swagger2markup.github.io/swagger2markup/1.3.3/#_pathsdocumentextension), seems like that can't be helped 😞

2024-07-01 15:12 UTC, merged